kind: pipeline
type: kubernetes
name: default

helm_deploy: &helm_deploy
  mode: upgrade
  release: castive3
  chart: ./castive3
  wait_for_upgrade: true
  atomic: true
  cleanup_failed_upgrade: true
  reuse_values: true
  kube_api_server: https://kubernetes.default
  kube_certificate:
    from_secret: kube_certificate
  client_certificate_data:
    from_secret: client_certificate_data
  client_key_data:
    from_secret: client_key_data


steps:
  # BUILD OCI IMAGE
  - name: publish
    image: harbor.v2.dcas.dev/library/drone-kaniko
    pull: always
    settings:
      registry: harbor.v2.dcas.dev
      repo: dcas.dev/castive3
      cache: true
      tags:
        - latest
        - ${DRONE_BRANCH/\//-}
      authjson_docker:
        from_secret: DOCKER_AUTH
    # LINT HELM CHART
  - name: helm_lint
    image: harbor.v2.dcas.dev/djcass44/drone-helm3
    settings:
      mode: lint
      chart: ./castive3
  # DEPLOY TO PROD
  - name: deploy_production
    image: harbor.v2.dcas.dev/djcass44/drone-helm3
    depends_on:
      - helm_lint
      - publish
    settings:
      <<: *helm_deploy
      namespace: production
      values:
        - ingress.host=dcas.dev
        - ingress.hsts="true"
        - netsec.enabled="true"
        - images.api.tag=latest
    when:
      branch:
        - master


trigger:
  when:
    event:
      - push