deploymentApiVersion: apps/v1
podAnnotations:
  k8s-app: dcas-dev
  linkerd.io/inject: enabled
security:
  podContext:
    fsGroup: 101
    runAsUser: 101
    runAsGroup: 101
  containerContext:
    runAsNonRoot: true
    privileged: false
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: false
service:
  externalPort: 8080
  internalPort: 8080
ingress:
  className: "gitlab-nginx"
  tls:
    enabled: true
    secretName: prod-dcas-dev
livenessProbe:
  path: "/healthz"
readinessProbe:
  path: "/healthz"
volumes:
  - name: tmp
    mountPath: /var/run
    config:
      emptyDir: {}
  - name: tmp2
    mountPath: /tmp
    config:
      emptyDir: {}
  - name: cache
    mountPath: /var/cache
    config:
      emptyDir: {}
resources:
  requests:
    memory: 25Mi
    cpu: 10m
  limits:
    memory: 50Mi
    cpu: 50m
networkPolicy:
  enabled: true
  spec:
    podSelector:
      matchLabels:
        k8s-app: dcas-dev
    ingress:
      - from:
          - podSelector:
              matchLabels:
                app: nginx-ingress
          - namespaceSelector:
              matchLabels:
                k8s-name: gitlab
