---
        {{- if .Values.netsec.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Chart.Name }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
                    {{- range $key, $val := .Values.netsec.namespace }}
                    {{ $key }}: {{ $val }}
              {{- end}}
        - podSelector:
            matchLabels:
                    {{- range $key, $val := .Values.netsec.source }}
                    {{ $key }}: {{ $val }}
            {{- end}}
      ports:
        - protocol: TCP
          port: 8080
        {{- end }}